# Generated by Django 3.2.6 on 2022-01-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.person')),
            ],
        ),
    ]
