# Generated by Django 3.2.6 on 2022-01-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='modified_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
